---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-credentials
  namespace: data-platform
spec:
  encryptedData:
    password: AgCMwlO9DAtiiSkrxN0vFdfnRoKUdIJsyN3e/vfJ0YINcW/aiqDiw28WoOey0TrQB6WsQ2FeRFotYmJofxYUs9DweGaN1KJ7pILKRwlPdUvJ+vpg/R34wBkQ/PnO51DNiQrLuW9BKi2F667Djcu7+SlriR2q1LD/HSaR33Eughp+IWofPbOxN93+pMC0/7894Ck3uWCsArgzzDWO+87P3Z6GZgmzg/1Ouh+qvX7/7Nf/tzSD3LNudHQtLMBSGN6wxBJVb+MobyBHeXVNBwdNJT2jv8SBMueCcT7UNyEeFQW03djY+Cl+ncoVstDEudpyxOXV9HKNY6yHx/4E5zNSncT9cdmYPqktr/0/6n2mS7o2hNDz5gjSvFjh9du6avTCDlRfndImnY0H2l7pn2d/xidl7DQXnG2FaqNsnaK5yQ/1iNYlq14M7nXIVPTnBwzwWIMF4SYGcyq6wAQ4vcboQ+dMed9lnRHIULV4TSvZSL3jc5jxC8SLnlfDe2YZRBcNw1kNlBOLF7W7Eg5cIh9GWWaqm5wfQQMajgOPZcvIf+M5v/ruc43lSym1rzlPzPSojKpviXD5H+qo38803c54Q3e94L6fZ5DI+HY90wX79WblHblYKgvJ9UHeJsPlP1GmryBfT12MsL4vHu+5PdO0w375TauAMWdob+gfPeUyc31m0zZzPwhetfGTLRJ1tr31vJcw1I0Amu8i0Xiqk/L14JNZBr8Q5ouKCNI6u1Ar8kmcsg==
    username: AgAF/vGhUcmQCJF3/tGKzvIdTrM/t4JkPBv6CMzqsBnNmMfeQet65L7tNhEvHg9DBVdk2JOgSqJRA5KjVsEA1Lf8m8SjalfTcjA9GB2Nu4UaCaAK1eGjeIdDRqY+YFCsMYsaAWsGILmcNKZnI3ky2RxxBwpAO2yEe0AKxwDZb2QhIome+RWGoWEbmHim21SSaBNEStdBZ2bG/DAWtmpz5Smxxrh+s1QuBdMk1t/Bkn4a876i5tC1U5TWOB70RW0/54LmSkhjuXQKnkNPK3iDn9Y+XSL2ZE4pxG25mrblOOMaxe0ggf0tkNylrUn25/+wQGeBW1t0ajSHPyfcyRm1ymh9OZfQmW9WJ8s5Dnrd0Q0drMoFCbp12nMftaPU673mTvHkVOXgeyMxFYWMPw6eTlyWFBZrvBQRZSayGX5Q9eAU5sq5KFVF2v2Fqkzsp7ilLgPlpnj82EL7MwlYKliy8rnfdzvB7dwU5eYFXpfjOFJnMimkR5bEvO0S27OEvEsxhhlAzgADmmcbperySM3zXGHj5cXJPkZATOUaQtBQqdECvxSl16AKQsxLCyDJPZeZNgTq3+Vglh6dZLENdMDFpkr3js8weWgdTnkK5DrswgRav2ZRs9DjTdyoXjjAJbo00WQh4c6N3a3fBB//JFas3uX88oIeIgcyi0I6HWRN22kI3tm9DhbJsD4KXFv+MbNujGoWf+fFb7hH
  template:
    metadata:
      name: airflow-credentials
      namespace: data-platform
    type: Opaque
