---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-credentials
  namespace: data-platform
spec:
  encryptedData:
    password: AgAzRVdmhF2b24gVOufREhyI2GIFs+UxlKondl8mSMFGFpp52uiMwDxZUtzf+W9TMql235y5wAtlPUTqabURhvIwW2dtHeRpljmsi2+CFH1RL3w3giJccic/kz30Z7BnSd5N9wj0hz7pUBsGZqVINjr8DOIEpkKmiZERpplHy2KGxbJyWtjCo0pW94jazv55zPiLyLQ0L94twYvxbw5dy1bg076b6wagqCGKULcFoxWO2VaBw9noreFKU7O2U8zRAOPYUHGj7fwRV+yp2sXcJs8HH91nYryhGEKV8VkBnW/FntTbRBDylzo8QXWOIZYMXLDvrc64oEZIZMHF7/IpYbmiQPXxl3/nrogvFTP/gfhY438s3M4PcL6CL6tJfcqJNBDDsirrP71nfWwpZ3b47HI+N/HDsJZIIeBbLPBDWoC6Ma5s5+1+S3UKAt/ifa/KuZyFBGE360ksYxLszqeN2fGBCNP4p6MylkDdwrNpY5C/+K6IVqd2QttPge1thG3hekqHeJBwnjd88lBGfUVK03CruUcIHaWQXnQcAHbmm8i58yK1NuRAVOHxs+q4b4htCLEjYBNTlN2IkxOqepKxPIgtVYjpkUjPw0eDWo3YOqVBPvMqCYUYaNqfSwxmvoCTWhrEDrCgQFWmxN6+z1oAei87K2D/Od5dSKroiDFi3ejXIGngiV5zvDCuqeR3565J2iL6FCYhCgUG5E9kJ0y7KAkLjS1ayT9GoKNQ+SqhhnoEYw==
    username: AgAJhwvDAymb3+qQRbLRH0Wbs7JG0OuZQZwVFzV/InvcqtpcLynQwS+hJe545ciTgaig9XsV17RrbiKtdOtGtziMGnMDFM54k9Hl8NhrxPm1kiIa0NgPOslMiYMyLCXewV9iQC/DPP5dKI8rjzGr9NeRLbbKfgzx0Z8OOUhYYDtLdgO58LvqmVEXOEeeXFCpT+JElInUyp4uFDjsJIFic0rktGuGArpRFORWIuSGpPTC1fub0fB36bux2gAydrnyb/phOCNv+oS38d728SiD8posEYqrCSIDy1pzHELRe65rKBnciEQzBT0RdUaHwa1ZefN2xuXGF3Cor8YfZeBj6xCHH6juN1aKoGoxoe0KkHlrVBqXv9hFXaNi0JBhFg4oX+0v0BvzO1galQMQRvgwCvT4Z9C76MRgSlvTCCdtmIo4JOGRpJV7EkIwVSdlSrchBqKWY2DzvKV/ACkY+1CKtPCFhXjK4eqXTA0EqMMYwhKeaCtAFHdP5SnCpgZ4I92V8I4sJmWdG7zrK2S4CX1f0hj+m06qkdKrt9wtIwymY9a0ihagQ+Ij/Rra9jL+zkiPIeN8mvPo+ODU9MKuxUWUr7VDUNWtAnD2tPO8nEZ16/oyKlLcwxWNFZHXBV0JLQrtA5lM/Fnff09KTRVXKo8qyw0/Sf+fuXZqs0lcA6c4MYFxRb2jlOQFaqOxMIKwgMxmCS7YACfX/fWE
  template:
    metadata:
      name: dagster-credentials
      namespace: data-platform
