---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lakekeeper-credentials
  namespace: data-platform
spec:
  encryptedData:
    password: AgCTpBFBgUoFnA2mKgcDa35sTQO0Gg3nKMfDm0HT49pwdO0/rPv71hld8hbjUXH7oamhqC5IC6OWLxVqV3irJliIxSvihWjAcfdPy9154wI34b3Pk9QcJjTL+hwNSNouw/XxF8JSTegOXg7loospvMFhtoPRNuaLP9KHK0SgXT7AUFvygdqgYg124QAmEnNNs3If/EXV90+avafm/WrXwDxHxphmeKeg+ZX7NBW9c9CiCBbPrUgSanMTuMBlwjSOyYHqM1rrYWCfEUUh5P4pHt/t81pipE2OXkdH171vAx8Ba7/C24T4x0y4jw96LSprBmixZ2OzesppatQtqAkcyCV1YuuNI9v7fnuFRcllDDQpwB2D6spYiJBlreTCx1NT2DIJM+pdDWjfjBYBys4rStyrwXSvIupY7GbuUpLBAb4L76lLd6m0d0DJ0eMbW7jzlgWhFCR+11WBhrF5tCxVpp4cZEBYnXtTV7IXibf8UyrdlnxZGLE7+0Nv9HVE0T3KXgNSxWvgsxf1wRbqWA3lTZ7rJbWh/NAcVtvrD48I9A1vTAGs3roKMjyrXCshofeSfXe5a3lUpoXu62JvhU4i/aSJic/aQrzN73FaKs17VBISebuBkX2gSci3hw3k+Sj8Iv3nEyb/5R+vfGD3GQ0poygrQPj8unKFXznqIu0mVhUn8tIQbvwfMb6Lyy7/cB3Zhgoet8VX0JjrYSwMoj15zgbuxkqltvDvn+Ml2GZpXF7Ytg==
    username: AgDGMsXnr8Bp9oksLeaQx0vIXYwnApX5hgPDrRMk70n/qOSOq8nPLj8ue/iLznWJtgXjig/K9rNXPkOX8ueLDDOOBwPf1grqAunqGAMgj+fsd7ulndEpN15gBmI+9116STmiFOmSSdpx98Ax7g8QVIiM/Z3f7kL1nkmVKgdztEMsZLZrIFSkZp3361DCoMPZ0H/cEF/Kv/AVdRw8p4I8eKlz1HMoXt2Fy6TOAEoNIFdmy50T/6XvcXjOQDdXbdG8qgsOSguEXQtcB6+ZKLCDbPmGTQX/jvAJ2mCUxgUdoy7Hrtaq17iQ3+HaPBPNYdgR6JK1D3zltg27JW9bSGjc06gR9fejuXXtpvAvjpyOCUBVcPFTBc7rH97/7N3InWfXjS9W6o2VVhw4RxmaYQjW4v554yMmDaInFe0J9OIYJJf3FtAZEy2kCsgdutFfbiTSixE9oLM1Z8eZ2RAr+Rygwz5b9CYrnKM6ENDqKeFcIYODDLMqO9S+KltCnpItWm8N0lSQcKPXNHGImmtSHASOD+aoYDklVq/VF6z0U2PppYN0QeEttKO7twRX6wdOktanEH498z6M4NpWYFkDg+hqb4V9w+O2DZWFy21m2ER/2mkoU5o1iRi3Bfg4NTRp80cD/GKvAFnUkpPc2CMHSI2pb0R9Dc6cmbNLKKPPHRtn5C8/mWHL0S5MmU5LYitlQOUTlveAB2f5LTzHi0/j
  template:
    metadata:
      name: lakekeeper-credentials
      namespace: data-platform
