---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root-credentials
  namespace: data-platform
spec:
  encryptedData:
    config.env: AgB6ErJQwi95hnwG2YLkn4xbDHbg9QYPAdY5GhSNxct4Gh3xJ1df8+Rlgq59pGeGVXBg55FOhKj7GVjsLVEoodkGaLS2gcFeC1eRd+rXxffmS3Fcglst4SOTeyHOwhPezJTROvVqTLCQ1pb6rDt99Rkg7LHISv8qHZmYFXelmT91dLmy24GW5mX+b5w84VTgLYlc3nQxygkAQrliZYHCpzv9gND4Y5nJxVFk8gm6wBaqHIza59WSaLwERT8u/n/KopIOyQg6Y6i5EiJN0ojcdq/Pprr3c6m+Ln8+YPir2WJrwXw50gRw42qsV8AZqibJSsajGc6XixoGpd7sKL5UsT113OGa/fNWafgHeVdb9/ToxN/yitwtucFdaAs4Qlsn/U7jfDuvGxmVvtbVhvgE8wxyQQNAGeT5wNLGleth2oDBiCOB9i4dFpgw5qUQ76zFNP8Ff+GgK81Bu21hFGe+T15e6JQ1sxY6OIYXA/6zQBLfeg6XzK/CTEp+WeSfIulx7X6Cn97NAsyrlolg8HzQuM7f1ondgx3oYfOfdq80DyH3OrdLrmEVqzaLoY/zhDXMbPWPSArg2X+pD/K2l757iAJzdi9xAUJAuRoCB2AUge1mndG1R51k9ACLfv9hoaYL2oOqbV6oh5N3dH7cgAWqkZ0vzw63UsKYDipg4f+oDjIJVIRFDIu/JIaQWWTIeKf6OpuM1vZl3O1N/8ZC9QDpAf4DAyUl1FpaEW7DEYLwwDC5F2S6GqRfh03tIR36scA+Bx3XL5T5LbLF1uk5yyNvb9LRmKUW8KXXYYe2XZXx9IUOcr9ZtwdHchCKug==
  template:
    metadata:
      name: minio-root-credentials
      namespace: data-platform
