---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-credentials
  namespace: data-platform
spec:
  encryptedData:
    password: AgCZycqwO9a7jN1o8oKdUZlsi4azPFK1oCp/DwgQ8ZoejOmc91Ji451rCHZfdT8QUhfF7CGrMwG+zE7FpW6NjW9eHinw4iA2Z+PeuoA9csCoVbNhKjuw73JHfiLt7BD3W+yASnrf0qpQuLntemITWlKqVZcj1uC/Y7x4ovqsFWyAKI4OK6u1X0H0HnFpUieiIEBwfcWxTQ5OTSE9nCuLqw2Rc++LxFSg6yOD0ZobnRB3H4CU9wxLSoryRYdLg3FlhndCQK9frFE+NybP6rj5h3FXxwgz1avxTEDXL1le2qaeYghRd9G9Rdu258uDbEM7va3JBnU0TNp9kQBv2nAPqMPviFu4jyYrS4EK9lZqqahwGeHWL863QK0I+UwhSQp0n+AirTJC1BSPMSBbAsgryomwRhwNS4eOf7a+AMyQX62ZvhkGG696HEU0EggOoPoFqZhZh1rwwVMf/D5kAHjC5Vk2alEsxrvhADMaXxCmF6VeMb4I/pc6izQlIFljb1euKBq55w69SIg2WnaGziKYioRyCMbo6VAh1PQHE/C7obp97V3sohkPYIySDc7+12Rt8s9R6v4E3gtmcT/zwmxJVyAOnRxT98TcLIWt1wcP6FQziaadSbk+9Sxxpet04bDsNOJB/IIc6pdD01xqSWsCPgghpdOeaV3HXAsnqvgDn2bW9tjX/kOm8vyDm63w+HqBbQQk6rNsa84q0m8btIRcNuie/SUQ2d2le04aD/NCLA0yoQ==
    username: AgAkYN0DDWYcFJdq1TFMhaaMIv5oLTXRogBEgOR5JV7VgIidhR4OIsbhx7F53GmK60BUXxyPpRBvBQVHqSrp6LzXaanxd4dUftSLqP7+1zE7bHcjIKhbqUX+5DSa+PEoSA1qw8kA86yTPVRgoQEsVFB6sBLDVCNTCZE0jlrIjSzKY8pnLWUfaWaOF7pu0A0bxJSKXhWHCIY3UzkXtggN56McYtUhrQASzwERGl0YbpM0YK/gpj7ngD7GGZ1Ce2pGPBtuZmxfAAV7WDN96F7ZrEMlqs7gbj3ra8Co+3p4DsFF81h4boLj0Myy17J+cFd3jUd0w2ZALBCEZBZWhrYAvRqOzfcTfiMeN4HEnRYR3i9D4LNbPSZJte4AP+wfZ4n7Qc/t12+W38QUb0WkDz4pyhEdQwneIhe4ftld21m16XGCjtbq9P+D/z13PMzEfqGSRjMw40q+qrd7vaAjtxQqalvqq6QjNnQksiFYJPY6F7nXdMVYjdNHezzbbRhpohpHMUjL6irA8Zu30fPePlE0TMjfLWo79h3Zib17D11lRYRM0PtgfnIeBMV+ZhNEhqNFUpApShjFGwe4R5lXSepz+HI/oLH/gKHcYm6i7Ry4vxmAyl/GLLDchhKB6Lu3FWf0jVmSvuF0Q1qGHRgzxrQT4blW7SnHa+8vZgCKGkHdqeB4TweE/CmVu8ep+XBbW2DGYDs20g1RJHg=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: mlflow
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: mlflow
      name: mlflow-credentials
      namespace: data-platform
    type: Opaque
