---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-backup-credentials
  namespace: data-platform
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBLIMBqZzdhvQWRKNt6RaaZ5J5YvWKXZTbCsQGKInz1iPY1olttlTOIbFkgja/9RblhHdq6XfQZUAGDSvlLV1KGHuaot6Wn28Vd4gmTbzY0K4tH9Pyb0BNOwAtTls1upaKs/3NWQf79yw0Eq+Hxz8T3krj614xwIOWffR3+vY7x4Y5FUauGuu3nJ5ThpO/esk25XJ5+fZk92bQirpGi//OxYl38yMBKoxfUngtF4Fx3wbKd6b9SZawuvmEY/R0VWME/8Aj+8l0NN8BLXJd+l5effEEC4mVmnZYKayuOYfVSZpGm56QxAL+Jvu/Tq2Q05ORF/aZvYug4bf+abeBX1bQiFgL4Q4JuksvfVbmfR5m0y1UuWohErtrVF2Ykd51KIQMzP4FIvr7s5J+TOHaMnIWPAmP6FAlmq+dvSsx5hVkX7fiAj+rhVcCS5xKj+J5BULj2v3hwmlQFLqidEN8ZIBj5+LQEjB8Dd0//GU2dNxWgI0HENYBXSe8x+cZc517VawHVjG8PWZIfBMIG1L82/i4fnQy6/xAeURKQOLCy83NuWCQx4QRGTg+Az3jmkc7P3t1DtPjA+QEieQKxQpm/yjJbxWo58o6KzF000gBsfyfuAyfe7fNoOO5Fb5An4/Rb8MKH9U18LZo+f2+64RHftUJC6GoiACI6sHv1S6/0FFWUoopYAG6SfmbVC/9WAxeSOw1pj1e4bNqtFi2WHxaNwsXiBjlilQ==
    ACCESS_SECRET_KEY: AgAqYzgupM1yZE59/7zVgAUVB+Ki7NbYO25kNTdpeBr6BLyewO2rOiyHZM31e9/JJb2oKHPCb0jejmRmny6bFiN59qxaElYKSNSlV/0kvKVxZy9rYIj30yL/tbTQRS6TBjGnAi26Nxyo25dzA6uHbOLwrsU2BYxEUxURzPA/3GVMI09j3WSrk4HGCGpWVuJryPthyQxAvLm4PKrwE7uX0A/j+D3erPXx3ywuNMPFUKbvVwX4NxyVZNgMf1fx+FEqXfgGoh3xj98/xIDXTvxKoWwNAtez6yCStq9LxhK1Nq36y735/qQ3X82Z3XhdgWooUEI3+rlQxr+JSMygBvx1plqNIBjEk+0EkxjzJUyk24K5j2TtiBMwW7ENK7wl1bzFueASpYw+g/cRjBGagfTmOSw0DTQuSH9Nw0Wr24EOwG6xRaRuxuUMwwAahb6H/ezc5DijHZFh47Ln2SM14QiLDkvVtJXG5kdxZpZt9lO2Wa8DSQQ/l4KJREPq6h2EQJm/MD1AqZkObcjIo4yYGNwcTJvS36rhos/VhFQZ8OUrZcKwXaqwUKHF+3nz2TaMJlG5QLDE9E3FSiJvrETnlxpwMblEGkxGVymXvXUNFjwvl2eVBhu1eAzmEoaDxLRCMvOEyEvCTD4PFMN/9BPo1ED4KiymAo/dHK55LSS8YdJLg4f+2HUt7gA4zfRkMVB/qBEh5XDBvcOw8iIPQtBH2TQ3dU7LURhoinoVoUC0hwJp2yAd4j0e4OchU3q3
  template:
    metadata:
      name: postgres-backup-credentials
      namespace: data-platform
