---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wedding-credentials
  namespace: application-data
spec:
  encryptedData:
    password: AgAWI9ngZnjeLL6CvVUXMJSMNC5t2kyJGgAGWjHiovqz8E+IfiIlr/5FQ0rBUpgGLEfBeYo3kay86xm96RyiHPfQCEu2K+JltogLo4gMeQ95OdPI4NuqkQ5e9Ai7bNScooAzVnGpMSLU6bEf0ki4hfnWEKU4isWnrRFZnTPGu0enJk7EcKqnaTCGZAoWiZ0kByQdC1+eYxmA8CZM8lohF26PcJAocXGvjA6+EUCvu7DjOGBXS20a5skCpjloKlZmNfTkCwTdABgGy5WUO3buCrTniscyR3rUzBA8GbMm9QTkLqNRviHiKpeaK69maHeLgXT8V12OOwZcroTi7bqepwW8A9WVunoWUruNI/Z4TC4bsaCoEzp4eP8kkdgBBmzCRr1avHrux+FxilalEK2MQOJgWzrbZ3oN7g92ZYF8Mn06BgwtZEYpH+hHt/UYM1gKWaxPTlCMZXOf1nn0d0yD+lMQPy3MdZzJ34OFPmX829BALvhGDmMiDyw/9q9q6NQuxt7yodYtiWctr5M/s2tfs5a1OYcye73eDLcX6w2Feo3+7ZuTpS06d0ZhyFoduxamaJOfyt2Mm9cbgPONxKhDzp0AP+ufMLOCA6TQCPerc8S3cXqpHjeSOnI/J/2spA5AFuZ7Lve/DAxF3e+RG4zeEkdugADPOjsG13QE4Z3K3JwICl3NR23htgrenCwvvsINbde8Avzp5LrkyYHf4R70aLokLuKMYk/r1Nnq0Ggydwn1Kw==
    username: AgAGwr01XmSmnYAtHbSXk+28eyNuQsG7KFkGzi3XJl5EqSoYLtJRKQ0f0LZgb3yvaMJDfrRR9EaLVvWU/UEpRskJ4J3KJE/NzZ+eDF6UIVwtZhFZke6WxNlhEzLXfjjtw5X0f3WaoGKSOo/GtYSWmFcpFKx7vYdMBJclSWbHrtF7JnyMVuLp12e6Zyb4nXrwkK2Kx1REFdkNHs41d7JnIKDlptZthb5tgtjQan8hTXvSp94wTKk3b2UzL/ZFqfY9+470GOx6dqd78QU0yV1J1EsfL2DIvJ8KIntPjfXf7n1eHnjAWhesJZV4EKAeu119/onYJnwKR4BbBLFvJM63HgIuxXO7zlHPzAKYMHcsVUUGgicc9oyy3TdZP6YAKA8jEKhlQ/Ir8WeohTkwkMN/LsmM/3Oz6RnrbUZneWWWGa+5oNrrFCSlqO21kHStLGxbCs5nYmKDrn9b6ZmEk749fNEVwrjevaVRmhtCIIdNhsS8N20eWEmSdzrHiaf3s3FbPu0L/zvkHjqwmi4t9exhckubCBXy3RKykExURv+/22I/jRZ7f4zF+pZBZXlBXTGLVG0P9zALpEarGVC7vf2OOrPeUK8qRGPvyn0urUnYJWDSzHMdoCrTSiic8UMXku6fO0XA6vpYk60YacOKm7MvaWug863XPkBUP6vpbb9iTTfjTR4bQJgxHweFAx5ZfOdy6S3f/vmDzrG+
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: wedding
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: wedding
      name: wedding-credentials
      namespace: application-data
    type: Opaque
