---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-s3-credentials
  namespace: mlflow
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDNW/tW2GvOjoz/EfSjF5N9thSSrfC0QIMalCgkQXgDgWvouQLvhbMFBMbGO16ftoweaMsew6YVYBgjqqwgtolO+rze+pEmQpJxlWDIFBRIQtzBY0EeTceTWLo+rehpmUnCVI/MzocTmvjyK2PQEWyqkBaUeXn8GdO0cSVk3TceUjtb9wRihJV/ZJfxDA41vw1fHJexb2dqkFeTgWAHg8OXRJhw093XatN6/5vzeliLao3WkwLWqbwdfR2ZYbrmXQ0cKqo8+OvJKUvuoyMUEdL3crAt/f7CZe35ieM5jR6ZKkHp7p6AGA3I7nq6fvb0za74DwBMW54ioLxbD+iV/cQ2IsDYi+iamh6Jl2ECK3hvMPc0IxK4/Quyeoaz8y691Q91JhqLb/mS9Vy6xmjXFUfDvYhoeEL5pWxZFn9dfQGX8D97G9bW863IHzbzFNVp2nY9SXothDANalsCxTD3Uhyjeh5fUZAIRXZGqKzRvC0PZ4y4kvuk39LDjsEVJ6n3A5EGlm2XYAHyGc85SMD46kN4ODstHfOAlqg3NfJgITU00EzYE7I9HszCH5y0zDZILaEK5BdsYPMPJfJnbb9DeE86/MzQY64rbfhZR+2/RzUdrc9sHIfPsHQCL37R6svBoUCLwmbzjCWb9jrNIaRr2OMq8KZGG4V8PzKj/O+k9hjoYb9UxTRusdUW4X7vUV9i5XYoagsN3A0s5NButhfX8S6JMiHcfg==
    AWS_SECRET_ACCESS_KEY: AgAHgib+z2r/5/Hp4Vqkb+X6AN+8xkZkjmP5DbiFlO0+kDvg/ErVrbiuHFh1uBn73IOgmd7ydcbvGNwphjQgLm6j0d93G1fJM4TmWW/TQX/NO7uSL9zEtfgEC4GeI0tpPWLsv7vSYwnZG54hhR7AGt/W04BM0yUOwUIfJ9r0lKfjMnFHQPDtm3jSlC2Ug96s5xgtinjvnZrIGq9gcit0pDyNukqev2FvDpQcjcDBmXzBQwKDXUCb2S4Xc6Gcns7rfk78C3waTX6xJGEusAbGzrx0s6XyiBVSLDk2WJfaQOuM7Kwn7h2CuCekhP/fZILm9+NHgc7lMgIVqopVYXYpms8VAe3s8wlWyht/wuOSL7heN6l243gslxOyEcxQBa6RARlR7Cv3JKZ0W/meS5w69o1S9GD+gcF1gqpX4bxKCx5ec8ispr2g5y4u+Kk+oYdSYAvy07Jlp2SgqurHILIKnclTtnuETTAI0yKcPyFE44WIUzLJwMRVkifDphIIB7otH6YY9zQqn2nh/xWhYkjq0WThlFPqYS30EowGOKY5o3Mea754jw1Uilj17VhtpEXQQP7tstoExqo3gB4vto0P6A11pOaZlTxJuaHd2ZiFNM4WKJEyghnBMS9V5Pc80u0+7oOGLiimeWqG4tr2tzyLgEyVuVS0kqKq07abf+acgZynBpLYpzFPWklN6LX1KbXkdm1TrtPGBH2pLyBi+XQdML816m8qM67ZJyfGjVrBpBp/pEU0T130H0X5
  template:
    metadata:
      name: mlflow-s3-credentials
      namespace: mlflow
