---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-s3-logs-credentials
  namespace: airflow
spec:
  encryptedData:
    AIRFLOW_CONN_AWS_S3_LOGS: AgAOEbUhjOXeWZmKTmbigxTngusk/57arJL+qAVOSmfggwP39QjPMEAZu7RSpYJXDmu0beKCIHrvsTVBi5CGBU08xmusU20cj8sLPR8qA8sS3a5Mimlph7Bwl8zht5kh6Fmp93sexZBiPWbbHqhk80e0U0VjiSHj/iTR/h4kuVvaVWTDOUvYy432TN0Z+n21saZQKJJydpXH/Zn5WVYHfflK+nmnjSNiO7g7MWrmgOffA2rZCmpGK/O+sTHLOw7SuhrGX0uENcE87VdHFzzxhaX5TCPr0pfZuEayvmUaF1g/1GDC6sYPIMzp6mJHVI98Ya8IpAQuSPdjcJWm47Zw7So0mm1GqsOYcgdF0COHDUmGqivW1gtS7DPnpJ+4u5nhXgOd5+VUWL52HiA4/mNJdSwzt1nm+mNz5ZyDY6xaAYxaxUTZp6twcjqHY86AcRzhihAbLmUaabZiLiCyjsga2nBTcxopeExo5ZF5pu0OkuLi0styjvunlHOyju6nUV3++btdjbvlMvlD9Ce0IeUAelH31xlVcknN57nUp3lAag5QgccF4NZVaWjQxXSZJpMPU9S17oTEMOBMvY56OwkuR9eVW1tzYHGDcdUlJojcWQ5Hg6VmEEER+9jm1CvgVoKZ7tLZkMG21R44ayE0fyzu1Xyjy2/4+iaQeOLLQgE/dncadWt3Prekt1k/JQfzUsGZP26oh8ctsf+G6CsmK9pNkoBer5Nq8yOrkp0aqRGp75N4vvWul1qqAVd29XtAoK8wYQmITMR/FbC5aajcSiLVhWZ5/yhmRnx6SoeoFVHkDjzab+PhQwZKU8dB+ulAIX0/yrHKqvfbsHfHFMk55WdOLf/N/Kts7ZcYGuxh1Rg/L0ZuxtHfbhf/bwdCyiqCnjPSGnNL6kDb1qmbsAn0eSnI4Ih1vDJkoB5Kr+GOH4Pg4by3aBuWR6UqBTiCMbYfOHdZ
  template:
    metadata:
      name: airflow-s3-logs-credentials
      namespace: airflow
    type: Opaque
