---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-jwt-secret
  namespace: airflow
spec:
  encryptedData:
    jwt-secret: AgA30q9Pi72922Y9hI8xJezqfD3fk3PHaWglwjHl7zlI90Iw5WEx/gU2LHIRIq/2yEXDMQe3Me+YaFYwLsTyIzNYrwjVY4/qR8/vGQxF4Diy8pCB0h2VRup1vtdFZsc3dmjBK22vRXX4mrRLbXPARZE9aCq0mrqSXn2OXGjSS3WmBvhKs6xlktujxRKk8VEI9hrg5kAtU6jNCvicOOum0gd7RfPVKFT/keJXmSuLaVkWDJn6zG7IALTTE3ah5JIZNFuBqy+NrbJXHshLMY69Mn2UPQVRL++RA/mNS/YRknsJ0CGOSnAeFgDYoUftAihwcMDPTZ9VTpqc9tFVg/wFBaFqjwpWpX30cfE1BDF+Dfk9fDEgfoSYi3CCNrwsB55wLpH2GsRiEoNwr/h4UVPfBfe4eWNn5ywmLMf46HEs//mZGGMNBiTb0GH3/rijgbJPLorfHXCBAPbahRifQSE6Z/W04jFVTDIPhB8k3FJrZm5nVjsmXsiDG8gpqbI/lagTbBOD+MELFBs4HFxW6itycNbvswjmJzx1dGSHpFCH0v6jdVH2MwVx/j+WzMqtkVirjxK3anMKsLmA2EnxgQtLnBHuOCn/0I2v7/DW7Wki/6Gt0ujg6gMgHfx5a31p8OJH0A4x82IoC4FNWe7WiQpCK+WV5C/MHnGQRg3ihXL6qIEenOhIcL3dQozEvLtU12bt6Lx5ZRgj960j1m0sZiiY+M0tMscdy0Zg2yw/XKRAZ6N6iX/Eiis53YGX5ED66w==
  template:
    metadata:
      name: airflow-jwt-secret
      namespace: airflow
    type: Opaque
