---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-api-secret
  namespace: airflow
spec:
  encryptedData:
    api-secret-key: AgA7nsvvWy5vjgt618jAUvdDQV12rPf6t/RzJeOcYZ2hF3Ij9bSSbMdXYymJaBnDoQffTLrkH9r8oCYrnVtTSM4USDeB+U/A9gOZxRAegEtguERxfQCWOz+adCubpO+pyOeghtBWWS7UbMuBVJJlWJX0vfRtpnYg8aklYneAC6nfODMh+pOHc/LgTCrnoZC1AW6PH1JKLNeX2NarXBigRjgaSTGy/Iqj0iKBPEE05xwjuFQ7o7Yea+SJKvSIYDN1uVrpg1o8EGvvIQHHnxRW362bWvHte/TRbG9tlyDMY0QLAOgib0RsHBUKUqVQfvdfJ8xq3Y6gF3Fo7uxjSYVNCSUBnS6VMV9lNgDMWIqQ51dtpHNh4j9/4T38uQohjikIMtem2CyYyuSa4tvpz4Xt+P1/k61hxmEaGAsoVIhrC+rp7BS6ggNvRotPWzrBDOoRw76hMlQpgxGZD29wys7lBT0ObY1Qnlg71oMFk/cFRmzuy2effMqGw5BBlLGufC4U3k62a76i/4oO8S8JaIl/ZiXfbQcO4SXK/uCXzc7Sw9Ze6dX3W6EVDKjL6aPQOYkwTCZ7XrCBbiRswwytnyLEPI0KEEOR57R19f91H4UTnOUYHjZW3QVAKlXi/IUPaWpASKGNecD+X3OpcYRA2tX1nPDfCLx2/NhQI2j4FeZZlT8TQHnk9XOVU+2Q97gQsfM3+dJewMone7o2iNAUz4RUR2CGX5N2LaF5ivBgSm9TOUKK6sGZAPxRyb4lOpqN7g==
  template:
    metadata:
      name: airflow-api-secret
      namespace: airflow
    type: Opaque
