---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insurance-retention-s3-credentials
  namespace: airflow
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgC0m+ORWm92CKIDyqjegnpEKZLtW5uXZQA88fDhgY7x4L22HTwrUT3oYat+4V/BuILhbev2O63BeFicSFHty848XFNiAb/N+BCc6sM8bgfdR2uBYfTbqZ1uNnYOVMTxUvoBospbTJ7aq0VZnPbgiVt2qEFsJ2uhDjjfZElaZ/RG5aLKcK/MrReSa94MjA+KGoyHJuAvowg8C2Nwo2sZTQ5aSFPjP0pLyZHAFYEudUvtMxBm9311a9yXvCYqWalVR1fpSuFvY0MYnuV3rG/W/qiuk7npv4Pu3JXuaNzRZFebwoDt1rPCPc46TA1ZpVWYDarUs9TYDQwllcsB+pHPwf6gyKVOHnebk4iAjw8QEppfc6PfyOsDZnDd6bLTSDwsLmlR5Bw4Cz58IBd9Y3u+S/+IU6gQOvs2O45vZVhRBmLePQLrk37KK4KIxqdE/Z27ZZkKiVlyQo3c6hHzw9ZobC17oXyeNJq0VKONOU9le3ua+dZ6R34+OLCqjPNhby43yVTh7RqVX80PlIPuFqUXQLFzvmsBEJWCPjR+kG/PNDRtWfoNX2N91+C95JGHBvPcsHu60AFnyP/ZVeoymKeBb/3zA2zoRK8TbolX0faigkBcRUgtlI22RihRyvmbC64cA1e7sGZn8/bxfLY0DO/+pyKsmm6XkTNCMbAM71aA36BbBa7uXFqjwR1GD4/UCW7XShDcKvA/JSjliwAtsppxGn0fLGacYQ==
    AWS_SECRET_ACCESS_KEY: AgB9bQQmFMkifD5X88FGfTkt8kXo2jes/JYryUvUCR7A5qyT/ALcu0/lwJpsOoFh/PzKUQnkGFYYhskg+CB5TfaBgaeLCjOgRdBMMoZCDQBM9uuNIh9N4JwFgbk31oQfqNLbqhE7/L8AwJf2lXOenKJOPQ4Ga/ZifuzhNfYre/8M8Hm4E0/NybUuVitl0xWbKfR1yXgohvp6ckP3PNDlNmaYxR4HW2D4YqIW//XgPTqJvDquNyOwL9RHQHS4oiQzHUaZ1RxCaEsqRSAabGCmXMtjpdmo8KzmAFuJ22hXRHTNC+Ad1MriBxpKIN6N/eRABmrbiGTz9/W+0yJUoOkZNcVUkmc7zpCSOOpMpHWjssx7d+3sBPtPKzRsB7rYrC+SleI30QBTmmBIcEHBoL/LpHf3Qb6ZGB4SufN8l4Y1XElIVcCybh3ooUR2ND+SvK3bQ+5Qm6FgxrZor1GbRnLXUQY11Fo93rcosbL6gAc/AcVpQzPDBc6wXlDJGImn6pb/xMZnIDKGNclCJVx/nIrr4cBe4AZmbovFrciA8mJEds1jQsnrooGaqW61do/TI6ddFZoJ0wkEEI2TGlZD+cIkrTYn0dQRSR5D408x02fMw/4N4UjaYOmhhoQsD0Cnx5ATz5epqse/eQcFFI5/bH0zN7npWPXwt091T0sKRBQV0AtGLdPhgPIJ305mBnTiqBVFbw08D2onKnN5EGgivDIvmwtiVCcPBPIGM4DU44rCcY/Y09OP+8nrLA2E
  template:
    metadata:
      name: insurance-retention-s3-credentials
      namespace: airflow
    type: Opaque
