---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: turnstile-credentials
  namespace: portfolio-site
spec:
  encryptedData:
    secret: AgCkgcU7PiMABZZs57Ciw3NTXPOAFPtkUyMjUx+b/vNjycnNcMmnVVNY3fHGhSd3B7xkp1dEME9HUyLiFJZjYeC9MuLHeVLoF6hRsos9YjS44djVixrUFmnwqj80imLQollbQ9V8UOya8HeYM8TBeeiq4XT0GMZ/+g4JKEbFumQygs3on5uzZKX9ZpFQPDNYCj6bx3SZbY6+LkqrqRn87e3g6NKm9h4k0sIhq2kl6pzRyL1NbaU+FofLGafmfbzHb28mhSYSEL8y/THwZumI114XRoOz0k5NxxzB262ic0HA5Aw5Fd4WSGzmerjRXjZu56R2MQXg0Ewpg4Sz315k1dv6qScXbxueNYpMc0wbWSLfqU0UziGodyWoNq+U/+lOpwPYzS0K8bkPw11GyLBjzkJkzDymVC3HjhR6huvZHNAM8cNHx001HK6yQzjZRinDxsE002AgLNI1g2U/Dem6uHjpsxVFXnAQA4rFeeYoYyrQuPg7g4WjMa/WveXo/E5f1n7FqVRoVeDbVfTT5eqCPmQ7eajPB3NA7X2n7GB+1+zx5D1f2fwV5fEFXj/4zp+EjrAkq4oD1S7Zl8j1zAyu8CDgyaLqRX63oLHrnB1lBDu+7I5IqF42j6BM/yVl38b20rVppP9opXBldEvynROSVqgafjrwIxzzNLAJwarrqVrHszMzMFrOw0K1lmwNW0PltRj2h7A5xLvsc7A74Q/hiBjvmWHvk7jicrU3FuFi0+H5Mor6oQ==
  template:
    metadata:
      name: turnstile-credentials
      namespace: portfolio-site
